package sshconfig

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/codemoo/hmux/internal/model"
)

func Render(inventory model.Inventory) ([]byte, error) {
	if err := inventory.Validate(); err != nil {
		return nil, err
	}
	refs := map[string]string{}
	for _, ref := range inventory.IdentityRefs {
		refs[ref.ID] = ref.Path
	}
	aliases := map[string]string{}
	for _, host := range inventory.Hosts {
		aliases[host.ID] = host.SSHAlias
	}
	hosts := append([]model.Host(nil), inventory.Hosts...)
	sort.Slice(hosts, func(i, j int) bool { return hosts[i].SSHAlias < hosts[j].SSHAlias })
	var out bytes.Buffer
	fmt.Fprintln(&out, "# Generated by hmux-control. Manual edits will be overwritten.")
	fmt.Fprintf(&out, "# schema=%d revision=%s\n\n", inventory.SchemaVersion, safeComment(inventory.Revision))
	for _, host := range hosts {
		fmt.Fprintf(&out, "Host %s\n", host.SSHAlias)
		fmt.Fprintf(&out, "    HostName %s\n", host.Address)
		fmt.Fprintf(&out, "    User %s\n", host.User)
		fmt.Fprintf(&out, "    Port %d\n", host.Port)
		if host.ProxyJump != "" {
			fmt.Fprintf(&out, "    ProxyJump %s\n", aliases[host.ProxyJump])
		}
		fmt.Fprintf(&out, "    IdentityFile %s\n", refs[host.IdentityRef])
		fmt.Fprintln(&out, "    IdentitiesOnly yes")
		fmt.Fprintln(&out, "    ForwardAgent no")
		fmt.Fprintln(&out, "    StrictHostKeyChecking ask")
		interval := host.ServerAliveInterval
		if interval == 0 {
			interval = 30
		}
		count := host.ServerAliveCountMax
		if count == 0 {
			count = 3
		}
		timeout := host.ConnectTimeout
		if timeout == 0 {
			timeout = 10
		}
		fmt.Fprintf(&out, "    ServerAliveInterval %d\n", interval)
		fmt.Fprintf(&out, "    ServerAliveCountMax %d\n", count)
		fmt.Fprintf(&out, "    ConnectTimeout %d\n\n", timeout)
	}
	return out.Bytes(), nil
}

func safeComment(value string) string {
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, value)
}
