package webgateway

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/codemoo/hmux/internal/filestage"
)

// The fixture is generated by the running Go upload validators with synthetic
// metadata and spool paths. Rust deliberately rejects duplicate JSON fields.
func TestRustUploadOracle(t *testing.T) {
	const csrf = "synthetic-csrf"
	const requestID = "0123456789abcdef0123456789abcdef"
	const stageID = "abcdef0123456789abcdef0123456789"
	const expires = int64(1790000000)
	start := `{"type":"start","csrf":"synthetic-csrf","session":{"id":"$12","created_at":123},"files":[{"size":2,"extension":"txt"},{"size":3}]}`
	type startCase struct {
		Name      string           `json:"name"`
		JSON      string           `json:"json"`
		GoValid   bool             `json:"go_valid"`
		RustValid bool             `json:"rust_valid"`
		Header    filestage.Header `json:"header,omitempty"`
	}
	startInputs := []struct {
		name, body string
		strict     bool
	}{
		{"valid", start, true},
		{"empty_extension_null", strings.Replace(start, `"size":3`, `"size":3,"extension":null`, 1), true},
		{"missing_extension", start, true},
		{"null_size", strings.Replace(start, `"size":2`, `"size":null`, 1), true},
		{"zero_size", strings.Replace(start, `"size":2`, `"size":0`, 1), true},
		{"bad_extension", strings.Replace(start, `"extension":"txt"`, `"extension":"TXT"`, 1), true},
		{"bad_session", strings.Replace(start, `"$12"`, `"12"`, 1), true},
		{"bad_created_at", strings.Replace(start, `"created_at":123`, `"created_at":0`, 1), true},
		{"csrf_mismatch", strings.Replace(start, csrf, "wrong", 1), true},
		{"unknown_start", strings.Replace(start, `"type":"start"`, `"type":"start","extra":1`, 1), true},
		{"unknown_file", strings.Replace(start, `"size":2`, `"size":2,"name":"private"`, 1), true},
		{"duplicate_type", strings.Replace(start, `"type":"start"`, `"type":"bad","type":"start"`, 1), false},
		{"trailing", start + `{}`, true},
		{"array", `[]`, true},
		{"null", `null`, true},
		{"empty_files", strings.Replace(start, `[{"size":2,"extension":"txt"},{"size":3}]`, `[]`, 1), true},
		{"too_many_files", strings.Replace(start, `[{"size":2,"extension":"txt"},{"size":3}]`, `[`+strings.TrimSuffix(strings.Repeat(`{"size":1},`, 17), ",")+`]`, 1), true},
	}
	var starts []startCase
	for _, input := range startInputs {
		var parsed browserUploadStart
		valid := strictUploadJSON([]byte(input.body), &parsed) == nil && parsed.Type == "start" && parsed.CSRF == csrf
		var header filestage.Header
		if valid {
			var err error
			header, err = browserUploadHeader(parsed)
			valid = err == nil
		}
		if valid {
			header.RequestID = requestID
		}
		starts = append(starts, startCase{input.name, input.body, valid, valid && input.strict, header})
	}
	var parsed browserUploadStart
	if err := strictUploadJSON([]byte(start), &parsed); err != nil {
		t.Fatal(err)
	}
	header, err := browserUploadHeader(parsed)
	if err != nil {
		t.Fatal(err)
	}
	header.RequestID = requestID
	sumA := sha256.Sum256([]byte("ab"))
	sumB := sha256.Sum256([]byte("cde"))
	hashes := []string{hex.EncodeToString(sumA[:]), hex.EncodeToString(sumB[:])}
	response := filestage.Response{
		ProtocolVersion: 1, RequestID: requestID, StageID: stageID,
		Session: header.Session, ExpiresAtUnix: expires,
		Files: []filestage.StagedFile{
			{Index: 0, Path: "/synthetic/staged-files-v1/1790000000-" + stageID + "/file-0001.txt", Size: 2, SHA256: hashes[0]},
			{Index: 1, Path: "/synthetic/staged-files-v1/1790000000-" + stageID + "/file-0002", Size: 3, SHA256: hashes[1]},
		},
	}
	base, err := json.Marshal(response)
	if err != nil {
		t.Fatal(err)
	}
	type responseCase struct {
		Name      string `json:"name"`
		JSON      string `json:"json"`
		GoValid   bool   `json:"go_valid"`
		RustValid bool   `json:"rust_valid"`
	}
	responseInputs := []struct {
		name, body string
		strict     bool
	}{
		{"valid", string(base), true},
		{"request_mismatch", strings.Replace(string(base), requestID, stageID, 1), true},
		{"stage_uppercase", strings.Replace(string(base), stageID, strings.ToUpper(stageID), 1), true},
		{"session_mismatch", strings.Replace(string(base), `"created_at":123`, `"created_at":124`, 1), true},
		{"expiry_zero", strings.Replace(string(base), `"expires_at_unix":1790000000`, `"expires_at_unix":0`, 1), true},
		{"wrong_hash", strings.Replace(string(base), hashes[0], strings.Repeat("0", 64), 1), true},
		{"wrong_size", strings.Replace(string(base), `"size":2`, `"size":3`, 1), true},
		{"wrong_index", strings.Replace(string(base), `"index":0`, `"index":1`, 1), true},
		{"parent_traversal", strings.Replace(string(base), `/synthetic/staged-files-v1/`, `/synthetic/../staged-files-v1/`, 1), true},
		{"wrong_directory", strings.Replace(string(base), `/staged-files-v1/`, `/other/`, 1), true},
		{"wrong_filename", strings.Replace(string(base), `/file-0001.txt`, `/file-0001.bin`, 1), true},
		{"relative_path", strings.Replace(string(base), `/synthetic/staged-files-v1/`, `synthetic/staged-files-v1/`, 1), true},
		{"newline_path", strings.Replace(string(base), `/file-0001.txt`, `\\n/file-0001.txt`, 1), true},
		{"unknown_response", strings.Replace(string(base), `"protocol_version":1`, `"protocol_version":1,"extra":1`, 1), true},
		{"unknown_staged_file", strings.Replace(string(base), `"index":0`, `"index":0,"extra":1`, 1), true},
		{"duplicate_version", strings.Replace(string(base), `"protocol_version":1`, `"protocol_version":0,"protocol_version":1`, 1), false},
		{"trailing", string(base) + `{}`, true},
		{"array", `[]`, true},
		{"null", `null`, true},
	}
	var responses []responseCase
	for _, input := range responseInputs {
		decoded, err := filestage.DecodeResponse([]byte(input.body))
		valid := err == nil && filestage.ValidateResponseForHeader(decoded, header, hashes) == nil
		responses = append(responses, responseCase{input.name, input.body, valid, valid && input.strict})
	}
	fixture := struct {
		CSRF      string           `json:"csrf"`
		Header    filestage.Header `json:"header"`
		Hashes    []string         `json:"hashes"`
		Starts    []startCase      `json:"starts"`
		Responses []responseCase   `json:"responses"`
	}{csrf, header, hashes, starts, responses}
	raw, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	path := filepath.Join("..", "..", "tests", "fixtures", "upload-v1", "go-oracle.json")
	if os.Getenv("UPDATE_HMUX_RUST_UPLOAD_FIXTURE") == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, raw, 0644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(raw, want) {
		t.Fatal("Go upload oracle changed")
	}
}
